export const GAMES = [
  { id: '01', path: '/01', title: 'Disturbance Field', desc: 'Disturb pixels without touching your trail' },
  { id: '02', path: '/02', title: 'Red Pixel Census', desc: 'Count true red while dodging' },
  { id: '03', path: '/03', title: 'One Frame Too Late', desc: 'Your avatar lags behind you' },
  { id: '04', path: '/04', title: 'Hex Taxonomy', desc: 'Classify symbols in rotating sectors' },
  { id: '05', path: '/05', title: 'Negative Space Surgeon', desc: 'Carve safe space from particles' },
  { id: '06', path: '/06', title: 'Cursor Must Not Understand', desc: 'Zones change how you move' },
  { id: '07', path: '/07', title: 'The Floor Is Previously Clicked', desc: 'Clicked UI becomes deadly' },
  { id: '08', path: '/08', title: 'Impossible Stopwatch', desc: 'Click invisible beats' },
  { id: '09', path: '/09', title: 'Static Oracle', desc: 'Find signals in static' },
  { id: '10', path: '/10', title: 'Reflex CAPTCHA', desc: 'Absurd security checks' },
  { id: '11', path: '/11', title: 'Wound Around a Word', desc: 'Type letters that move' },
  { id: '12', path: '/12', title: 'Pixel Debt', desc: 'Every pixel costs you later' },
  { id: '13', path: '/13', title: 'The Unfair Metronome', desc: 'Move only on the right beats' },
  { id: '14', path: '/14', title: 'Live Inventory Tetris', desc: 'Pack living items fast' },
  { id: '15', path: '/15', title: 'Color Command Contradiction', desc: 'Stroop arena collapse' },
  { id: '16', path: '/16', title: 'Breathe or Die', desc: 'Sync with the breathing circle' },
  { id: '17', path: '/17', title: 'Borderline', desc: 'Survive on the viewport edge' },
  { id: '18', path: '/18', title: 'The Last Safe Pixel', desc: 'One safe pixel at a time' },
  { id: '19', path: '/19', title: 'Mitosis Pong', desc: 'Find the real ball' },
  { id: '20', path: '/20', title: 'Noise Chef', desc: 'Catch recipe ingredients' },
  { id: '21', path: '/21', title: 'Parallax Lie Detector', desc: 'Only one layer is real' },
  { id: '22', path: '/22', title: 'Tethered to Your Mistake', desc: 'Ghosts replay your moves' },
  { id: '23', path: '/23', title: 'Minimum Viable Apocalypse', desc: 'Every step corrupts the grid' },
  { id: '24', path: '/24', title: 'The Game Hates Straight Lines', desc: 'Varied motion or die' },
  { id: '25', path: '/25', title: 'Blackout Debugger', desc: 'Navigate invisible mazes' },
];
